[[questions]]
type = "MultipleChoice"
prompt.prompt = "Warum kann `mapTimesTwo` eine Liste entgegennehmen und eine Liste zurückgeben?"
prompt.distractors = [
  "Weil Listen keine Werte sind und deshalb überall durchgereicht werden.",
  "Weil Methoden nur Listen verarbeiten dürfen.",
  "Weil Rückgabewerte immer Listen sein müssen."
]
answer.answer = "Weil Listen Werte wie alle anderen sind und deshalb als Parameter und Rückgabewerte dienen können."
context = "Listen sind Werte. Wie jeder Wert können sie an Methoden übergeben und von ihnen zurückgegeben werden."
id = "fe39e713-50fd-4fd6-827c-db02c0f1cc27"
