[[questions]]
type = "MultipleChoice"
prompt.prompt = "Was passiert, wenn `luca.getOlder()` zweimal hintereinander aufgerufen wird?"
prompt.distractors = [
  "Das Alter erhöht sich nur einmal, weil der zweite Aufruf ignoriert wird.",
  "Es entsteht ein Fehler, weil Methoden nur einmal aufgerufen werden dürfen.",
  "Es wird ein neues Objekt mit dem doppelten Alter erzeugt."
]
answer.answer = "Das Alter im Objekt `luca` erhöht sich insgesamt um 2."
context = "Jeder Methodenaufruf verändert das bestehende Objekt weiter."
id = "54a6d3ac-3827-49a4-86b9-2afd6542bac5"
