[[questions]]
type = "MultipleChoice"
prompt.prompt = "Was unterscheidet Methoden in einer `class` von Methoden in einem `record`?"
prompt.distractors = [
  "In einer `class` können keine Methoden definiert werden.",
  "Methoden in einer `class` haben keinen Rückgabetyp.",
  "In einem `record` sind Methoden immer privat."
]
answer.answer = "In einer `class` können Methoden Eigenschaften des Objekts verändern, in Records nicht."
context = "Records sind unveränderlich, während Klassen veränderbare Eigenschaften erlauben."
id = "92e08bf0-434f-4365-b02b-1b459b0e4afe"
