[[questions]]
type = "MultipleChoice"
prompt.prompt = "Welchen Rückgabetyp hat eine Methode wie `getOlder()`, wenn sie nur den Zustand ändert?"
prompt.distractors = [
  "`int`",
  "`null`",
  "`boolean`"
]
answer.answer = "`void`"
context = "Wenn eine Methode keinen Wert zurückgibt, sondern nur einen Effekt hat, verwendet man `void`."
id = "43090036-3953-456d-8fb4-431862ddeecd"
